name: Publish a Release

# See ./reusable-release.yml for required secrets

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The new version of the pack"
        required: true
        type: string
      update-version:
        description: "If the version should be updated"
        type: boolean
        default: true
      release-type:
        description: "Release type, should basically always be release. Beta and Alpha both trigger pre-releases on github"
        required: true
        type: choice
        default: release
        options:
          - alpha
          - beta
          - release

# Cancel any ongoing instances of this workflow
concurrency:
  group: release
  cancel-in-progress: true

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable-release.yml@main
    with:
      version: ${{ inputs.version }}
      update-version: ${{ inputs.update-version }}
      release-type: ${{ inputs.release-type }}
    secrets: inherit
